flickpic/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('movies/', views.movies_index, name='index'),
path('accounts/signup/', views.signup, name='signup'),
path('movies/create/', views.MovieCreate.as_view(), name='movies_create'),
path('movies/<int:movie_id>/add_review/', views.add_review, name='add_review'),
path('movies/<int:pk>/review_delete/', views.review_delete, name='review_delete'),
path('movies/<int:pk>/review_update/', views.review_update, name='review_update'),
path('movies/<int:movie_id>/assoc_review/<int:review_id>/', views.assoc_review, name='assoc_review'),
path('review/<int:pk>/', views.ReviewDetail.as_view(), name='review_detail'),
path('movies/<int:movie_id>/', views.movies_detail, name='detail'),
path('movies/search_movies/', views.search_movies, name='search-movies'),
path('favorites/', views.favorites, name='favorites'),
path('favorites/<int:id>/', views.add_to_favorites, name='add_to_favorites'), 
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


GENRES = (
   ('Romantic Comedy','Romantic Comedy'),
   ('Thrillers','Thrillers',),
   ('Drama','Drama'),
   ('Comedy','Comedy'),
   ('Documentary','Documentary'),
   ('Family','Family')
)



class Movie(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.CharField(max_length=250)
    movielink = models.CharField(max_length=250, default = '')
    movieposter = models.CharField(max_length=250)
    genre = models.CharField(
		max_length=15,
		#choices
		choices=GENRES,
		default=GENRES[0][0]
	)
    class NewManager(models.Manager): 
        def get_queryset(self):
            return super().get_queryset() 
    favorites = models.ManyToManyField(User, default=None, blank=True) 
    objects = models.Manager()
    newmanager = NewManager()
    def __str__(self):
        return f"The Movie {self.name} has id of {self.id}"

class Review(models.Model):
    comment = models.CharField(max_length=100)
    recommend = models.BooleanField('Would Recommend')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default = '1')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"The user {self.user} has id of {self.id} and {self.recommend}"

    def get_absolute_url(self):
        return reverse('review_detail', kwargs={'pk': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Review
from django import forms 


class ReviewForm(forms.ModelForm):
    recommend = forms.BooleanField(required=False)
    class Meta:
        
        model = Review
        fields = ['comment','recommend' ]

    

main_app/views.py
from operator import contains
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from main_app.models import GENRES, Movie, Review
from .forms import ReviewForm
from django.contrib.auth.models import User



S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'myimagebucket28'

def search_movies(request):
  if request.method == "POST":
    searched = request.POST['searched']
    movies = Movie.objects.filter(genre__icontains=searched)
    return render(request,
    'movies/search_movies.html',
    {'searched': searched,
    'movies': movies})
  
  else:
    return render(request,
    'movies/search_movies.html',
    {})


def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

# Add the following import
from django.http import HttpResponse

# Define the home view
def home(request):
  return render(request,'home.html')



def movies_index(request):
  movies = Movie.objects.all()
  return render(request, 'movies/index.html', {'movies': movies})

class MovieCreate(LoginRequiredMixin,CreateView):
  model = Movie
  fields = ['name', 'description', 'genre']
  
  # This inherited method is called when a
  # valid cat form is being submitted
  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
    return super().form_valid(form)


@login_required
def add_review(request, movie_id):
  # if request.method == "POST":
  #   
	# create a ModelForm Instance using the data in the request
  form = ReviewForm(request.POST)

	# validate
  if form.is_valid():
    user = request.user
    
  
		# do somestuff
		# creates an instance of out review to be put in the database

  new_review = form.save(commit=False)
  new_review.movie_id = movie_id  
  new_review.user = user
  new_review.save() 
    

  return redirect('detail', movie_id=movie_id)

def review_delete(request, pk):
    review = get_object_or_404(Review, pk=pk)  

    if request.method == 'POST':         # If method is POST,
        review.delete()                     # delete the review.
        return redirect('/movies/')             # Finally, redirect to the homepage.

    return render(request, 'review_delete.html', {'review': review})
    # If method is not POST, render the default template.
    # *Note*: Replace 'template_name.html' with your corresponding template name.
  
def review_update(request, pk):
    context = {}
    review = get_object_or_404(Review, pk=pk)
    form = ReviewForm(request.POST or None, instance = review)
    if form.is_valid():
      form.save()
      return redirect('/movies/')


    context["form"] = form

    return render(request, 'review_update.html', {'review': review})




def assoc_review(request, movie_id, review_id):
  Movie.objects.get(id=movie_id).reviews.add(review_id)
  return redirect('detail', movie_id=movie_id)

class ReviewDetail(LoginRequiredMixin,CreateView):
  model = Review
  fields = ['comment', 'recommend']



class ReviewUpdate(LoginRequiredMixin,UpdateView):
  model = Review
  fields = ['comment', 'recommend']

class ReviewDelete(LoginRequiredMixin,CreateView):
  model = Review
  fields = ['comment', 'recommend']
  success_url = '/movies/'

def movies_detail(request, movie_id):
  

    movie = Movie.objects.get(id=movie_id)
    # create an instance of ReviewForm
    review_form = ReviewForm()
    favorite = bool
    if movie.favorites.filter(id=request.user.id).exists(): #checks if the user's id exists and see if they have added the movie to their favorites page
      favorite = True
    return render(request, 'movies/detail.html', {'movie': movie, 'review_form': review_form, 'favorite': favorite
    
    })
    
#this renders the favorites page
@login_required
def favorites(request): 
    new = Movie.newmanager.filter(favorites=request.user) #this filters newmanager inside of the Movie model; returns the data returned from the database 
    return render(request, 'movies/favorites.html', {'favorites': favorites, 'new': new}) #pass in variables for the favorites template


@login_required
def add_to_favorites(request, id):
    #the get_object_or_404 is a Django shortcut that calls get() on a model manager,
    #but it gives Http404 to return the standard error page
    movie = get_object_or_404(Movie, id=id) #pass in the Movie model and the id of the movie
    if movie.favorites.filter(id=request.user.id).exists(): #checks to see if the user id exists inside of the favorites field in the Movie model
        movie.favorites.remove(request.user) #if it exists, then remove it 
    else:
        movie.favorites.add(request.user) #else, add the id of user 
    return redirect('/favorites/') #redirect to the favorites page
    
    

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>QuickFlix</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav class="nav">
                <div class="nav-wrapper">
                    <ul>
                        <li><a href="/" class="left"><img src="https://quickflix.s3.us-west-1.amazonaws.com/logos/QUICKFLIX.svg" alt=""></a></li>
                    </ul>
                    {% if user.is_authenticated %}
                    <div class="center">
                        <ul class="search-nav">
                            <li>
                                <form method="post" action="{% url 'search-movies' %}" class="input-field">
                                {% csrf_token %}
                                <input type="search" placeholder="Search Genres" aria-label="Search" name="searched" id="search">
                                <button class="btn-small btn-outline-secondary" type="submit" id="search-btn">Search</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                    <ul class="right user-name">
                        <li><a class='dropdown-trigger' href='#' data-target='dropdown1'>{{ user }}</a></li>
                            <ul id='dropdown1' class='dropdown-content'>
                                <li class="dropdown-link"><a href="{% url 'index' %}">All Movies</a></li>
                                <li class="dropdown-link"><a href="{% url 'favorites' %}">My Favorites</a></li>
                                <li class="dropdown-link"><a href="{% url 'logout' %}">Log Out</a></li>
                            </ul>
                    </ul>
                        {% else %}
                    <ul class="right">
                        <li><a href="{% url 'index' %}">All Movies</a></li>
                        <li><a href="{% url 'signup' %}" class="btn-small">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                    </ul>
                </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="center"><p class="footer-text">All Rights Reserved, &copy; 2022 QuickFlix</p>
    </div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="col flex-box">
    <div class="about">
        <h1>A quicker way to pick your flick</h1>
        <p>QuickFlix is an app that brings the best movies of Netflix, Hulu, and Amazon Prime to one place. The user can search through all three libraries simultaneously, cutting their search time in half.</p>
        {% if user.is_authenticated %}
        <!-- <div><a class="waves-effect waves-light btn-large" href="{% url 'logout' %}">Log Out</a></div> -->
        {% else %}
        <div><a class="waves-effect waves-light btn-large" href="{% url 'signup' %}">Sign Up</a></div>
        {% endif %}
        <div class="logos">
            <img class="img-logo" src="https://quickflix.s3.us-west-1.amazonaws.com/logos/netflix-logo.svg">
            <img class="img-logo" src="https://quickflix.s3.us-west-1.amazonaws.com/logos/hulu-logo.svg">
            <img class="img-logo" src="https://quickflix.s3.us-west-1.amazonaws.com/logos/prime-video-logo.svg">
        </div>
    </div>
    <div>
        <img src="https://quickflix.s3.us-west-1.amazonaws.com/hero-3d-person.png" srcset="https://quickflix.s3.us-west-1.amazonaws.com/hero-3d-person.png 2x">
    </div>
</div>
{% endblock %}

main_app/templates/main_app/review_form.html
{% extends 'base.html' %}

{% block content %}
	{% if object %}
		<h1>Edit <span class="teal-text">{{movie.name}}</span></h1>
	{% else %}
		<h1>Add Review</h1>
	{% endif %}
<!-- Leaving the action blank will use the same url that was used in order to get the form -->
<form action="" method="POST">
	{% csrf_token %}
	<table>
		Comment:{{ form.comment }}
		<label>
			<input type="checkbox" name="recommend">
			<span>Would Recommend {{ form.recommend }}</span>
			</label>
		</table>

	<input type="submit" value="submit!" class="btn" />
</form>
{% endblock content %}

main_app/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Movie Detail</h1>

<div class="row">
  <div class="col s6 m5 13 movie-poster"> 
    <div>
      <img src="{{movie.movieposter}}" alt="" class="responsive-img">
      <div><a class="waves-effect waves-light btn-large" href="{{movie.movielink}}" id="watch-btn">Watch Now</a></div>
    </div>
  </div>
    {% if favorite %}
    <div class="col s6"> 
      <div>
        <div><a class="waves-effect waves-light btn-small" href="{% url 'add_to_favorites' movie.id %}">Remove From Favorites</a></div>
      </div>
    </div> 
    {% else %}
    <div class="col s6"> 
      <div>
        <div><a class="waves-effect waves-light btn-small" href="{% url 'add_to_favorites' movie.id %}">Add To Favorites</a></div>
      </div>
    </div> 
    {% endif %}
    <div class="col s6">
      <div class="block">
        <p>Title: {{movie.name}}</p>
        <p>Genre: {{movie.get_genre_display}}</p>
        <p>Description: {{movie.description}}</p>
      </div>
    </div>
    <!-- <div class="col s6 m4 13 empty-div"></div> -->
    <div class="col s6 review">
      <h2>Add Review</h2>
      <form action="{%url 'add_review' movie.id %}" method="POST">
        {% csrf_token %}
        <table>
          {{ review_form.comment }}
          <label>
            <input type="checkbox" name="recommend"><span>Would Recommend {{form.recommend }}</span>
          </label>
        </table>
        <input type="submit" value="submit" class="btn" id="submit-btn"/>
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Reviews</th>
            <th>Recommendations</th>
          </tr>
        </thead>
        <tbody>
          {% for review in movie.review_set.all %}
          <tr>
            <td>{{review.user}} </td>
            <td>{{review.comment}} </td>
            <td>{{review.recommend|yesno:"Would Recommend,Would not Recommend" }}</td>
            {% if user == review.user %}
            <td><a href="{% url 'review_update' review.id %}" class="btn-small rec">Edit</a></td>
            <td><a href="{% url 'review_delete' review.id %}" class="btn-small rec">Delete</a></td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
</div>
{% endblock %}

main_app/templates/movies/favorites.html
{% extends 'base.html' %}

{% block content %}
<h1>My Favorites</h1>

<div class="row">
    {% for movie in new %}
        <div class="col s3 m3 13">
            <a href="{% url 'detail' movie.id%}">
                <img src="{{ movie.image }}" alt="" class="responsive-img">
            </a> 
        </div>
        {% endfor %}
    </div>

{% endblock content %}

main_app/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie List</h1>

<div class="movies-grid">
{% for movie in movies %}
<div class="movie">
    <a href="{% url 'detail' movie.id%}">
        <img src="{{ movie.image }}" alt="" class="responsive-img">
    </a>
</div>
    {% endfor %}
</div>

<!-- <div class="row">
{% for movie in movies %}
    <div class="col s3 m3 13">
        <a href="{% url 'detail' movie.id%}">
            <img src="{{ movie.image }}" alt="" class="responsive-img">
        </a>
    </div>
    {% endfor %}
</div> -->

{% endblock %}

main_app/templates/movies/search_movies.html
{% extends 'base.html' %}
{% block content %}

<div class="col">
   <div class="about">
      {%if searched%}
      <h2>You Searched For <span class="white-text">{{ searched }}</span></h2>
      <table>
         <thead>
            <tr>
               <th>Movie</th>
               <th>Movie Genre</th>
               <th>Movie Description</th>
            </tr>
         </thead>
         <tbody>
            <tr>
               {% for movie in movies %}
               <td><a href="{% url 'detail' movie.id%}"><img src="{{ movie.image }}" alt=""></a></td>
               <td>{{ movie.genre }}</td>
               <td>{{ movie.description }}</td>
            </tr>
         </tbody>
         {% endfor %}
      </table>
      {% else %}
      <h2> What would you like to Watch? </h2>
      {% endif %}
      
      {% if user.is_authenticated %}
      <!-- <div><a class="waves-effect waves-light btn-large" href="{% url 'logout' %}">Log Out</a></div> -->
      {% else %}
      <div><a class="waves-effect waves-light btn-large" href="{% url 'signup' %}">Sign Up</a></div>
      {% endif %}
   </div>
</div>
{% endblock %}

main_app/templates/review_delete.html
{% extends 'base.html' %}


{% block content %}
<h1>Delete Review</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'review_detail' review.id %}">Cancel</a>
</form>
	
{% endblock content %}

main_app/templates/review_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit review</h1>

<form method="POST">
	{% csrf_token %}
	<table>
        <label>
        <input type="text" name="comment" id="edit-input">
		{{ review_form.comment }}
    </label>
    <label>
			<input type="checkbox" name="recommend">
			<span>Would Recommend {{form.recommend }}</span>
			</label>
	</table>

	<input type="submit" value="Update" class="btn" />
</form>
    {% endblock %}